module.exports = {
  ShotsTypes: {
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
    REQUEST_FAILURE: "REQUEST_FAILURE",
    SCROLL_TO_BOTTOM: "SCROLL_TO_BOTTOM",
    PULL_TO_REFRESH: "PULL_TO_REFRESH",
    RESET_PULL_REFRESH: "RESET_PULL_REFRESH"
  }
  
};